<?php



/**
 * Implements hook_block_info()
 */
function my_blocks_block_info() {
	$blocks = array();
	
	$blocks['my_first_block'] = array(
		'info' => t('My custom block'),	
		'cache' => DRUPAL_NO_CACHE,
	);
	
	return $blocks;
}


/**
 * Implements hook_block_view()
 */
function my_blocks_block_view($delta = '') {
	$block = array();
	
	if ($delta == 'my_first_block)') {
		$block['subject'] = t('Block Subject');
		$block['content'] = t('Block content');
	}
	
	return $block;
}